[package]
name = "sine"
version = "0.1.0"
authors = ["AndreiSva <andreisva2023@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
crossterm = "0.19.0"
clap = "2.33.3"
ctrlc = "*"
